export default [
		{city: 'Chiyoda', code: 'chiyoda'},
		{city: 'Chuo', code: 'chuo'},
		{city: 'Minato', code: 'minato'},
		{city: 'Shinjuku', code: 'shinjuku'},
		{city: 'Bunkyou', code: 'bunkyou'},
		{city: 'Taitou', code: 'taitou'},
		{city: 'Sumida', code: 'sumida'},
		{city: 'Kotou', code: 'kotou'},
		{city: 'Shinagawa', code: 'shinagawa'},
		{city: 'Meguro', code: 'meguro'},
		{city: 'Outa', code: 'outa'},
		{city: 'Setagaya', code: 'setagaya'},
		{city: 'Shibuya', code: 'shibuya'},
		{city: 'Nakano', code: 'nakano'},
		{city: 'Suginami', code: 'suginami'},
		{city: 'Toshima', code: 'toshima'},
		{city: 'Kita', code: 'kita'},
		{city: 'Arakawa', code: 'arakawa'},
		{city: 'Itabashi', code: 'itabashi'},
		{city: 'Nerima', code: 'nerima'},
		{city: 'Adachi', code: 'adachi'},
		{city: 'Katsushika', code: 'katsushika'},
		{city: 'Edogawa', code: 'edogawa'}
	]