export default [
		{city: 'Chiyoda', code: 101},
		{city: 'Chuo', code: 102},
		{city: 'Minato', code: 103},
		{city: 'Shinjuku', code: 104},
		{city: 'Bunkyou', code: 105},
		{city: 'Taitou', code: 106},
		{city: 'Sumida', code: 107},
		{city: 'Kotou', code: 108},
		{city: 'Shinagawa', code: 109},
		{city: 'Meguro', code: 110},
		{city: 'Outa', code: 111},
		{city: 'Setagaya', code: 112},
		{city: 'Shibuya', code: 113},
		{city: 'Nakano', code: 114},
		{city: 'Suginami', code: 115},
		{city: 'Toshima', code: 116},
		{city: 'Kita', code: 117},
		{city: 'Arakawa', code: 118},
		{city: 'Itabashi', code: 119},
		{city: 'Nerima', code: 120},
		{city: 'Adachi', code: 121},
		{city: 'Katsushika', code: 122},
		{city: 'Edogawa', code: 123}
	]